name: 'deepset Cloud file uploader'
description: 'Upload file and metadata to deepset Cloud using GitHub Actions.'
author: 'Silvano Cerza'
inputs:
  api-key:
    required: true
    description: 'A valid deepset Cloud API Key'
  workspace-name:
    required: true
    description: 'deepset Cloud Workspace name'
  file:
    required: true
    description: 'File uploaded to deepset Cloud'
  meta:
    required: false
    description: 'File metadata formatted as a YAML map of strings'
    default: ''
  write-mode:
    required: false
    description: 'How to handle file upload in case a file with the same name already exists. Possible options are: KEEP, OVERWRITE, FAIL. Defaults to FAIL.'
    default: 'FAIL'
runs:
  using: 'node16'
  main: 'dist/index.js'
